# Workflow GitHub Actions pour exécuter pre-commit sur les PRs
# Version simplifiée pour la CI (sans Terraform)

name: Pre-commit checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit (skip terraform and some checks)
        run: |
          SKIP=terraform_fmt,terraform_validate,terraform_docs,terraform_tfsec,detect-secrets pre-commit run --all-files
        continue-on-error: true  # Ne pas bloquer si pre-commit échoue
